yaml-version: 1
services:

The service definition must start with a hyphen (-)
type: static
name: solid-web-creations
branch: main
buildCommand: npm run build
staticPublishPath: build
routes:

The route rule must also start with a hyphen (-)
type: rewrite
source: /* 
destination: /index.html
