yamlVersion: 1
services:
  - type: static
    name: solid-web-creations
    branch: main
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
